name: "create-pr"
description: "Creates and merges a pr"
inputs:
  title:
    description: "Title for the PR"
    required: true
  body:
    description: "Body for the PR"
    required: true
  github_token:
    description: "Token to be used for Github"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up git
      shell: bash
      run: |
        git config user.email git@pointjig.de
        git config user.name "Git Bot"
    - name: Create and merge PR
      shell: bash
      run: |
        git switch -c updates-${{ github.run_id }}
        git diff-index --quiet HEAD -- && echo "no changes" && exit 0
        git commit -am "flake.lock: Update"
        git push -u origin updates-${{ github.run_id }}
        PR=$(gh pr create \
          --assignee Shawn8901 \
          --base main \
          --body "${{ inputs.body }}" \
          --fill \
          --label bot \
          --title "${{ inputs.title }}")
        gh pr merge $PR --merge --delete-branch
      env:
        GITHUB_TOKEN: "${{ inputs.github_token }}"
