version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 5
  reviewers:
  - Shawn8901
  assignees:
  - Shawn8901
  labels:
  - CI
