name: Flake Updater

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

jobs:
  update_flake:
    runs-on: ubuntu-22.04
    outputs:
      packages: ${{ steps.gen_packages.outputs.packages }}
      machines: ${{ steps.gen_machines.outputs.machines }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GH_TOKEN }}"
      - name: Install nix
        uses: ./.github/actions/setup-env
        with:
          github_token: "${{ secrets.GH_TOKEN }}"
          netrc_content: "${{ secrets.NETRC_CONTENT }}"
          setup_cachix: false
      - name: Update flake
        run: nix flake update
      - name: Check Flake
        run: nix flake check --allow-import-from-derivation
      - name: Set up git
        shell: bash
        run: |
          git config user.email git@pointjig.de
          git config user.name "Git Bot"
      - name: Create commit and push to staging branch
        shell: bash
        run: |
          git diff-index --quiet HEAD -- && echo "no changes" && exit 0
          git commit -am "flake.lock: Update"
          git push origin HEAD:refs/heads/staging
