name: Nixpkgs Updater

on:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch: {}

jobs:
  sync_fork:
    runs-on: ubuntu-22.04
    steps:
      - name: Sync fork
        shell: bash
        run: |
          gh repo sync Shawn8901/nixpkgs --source NixOS/nixpkgs --branch master
          gh repo sync Shawn8901/nixpkgs --source NixOS/nixpkgs --branch nixos-unstable
          gh repo sync Shawn8901/nixpkgs --source NixOS/nixpkgs --branch nixos-24.11
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
  update-branch:
    runs-on: ubuntu-22.04
    needs: [sync_fork]
    steps:
      - name: Clone config repo
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          token: "${{ secrets.GH_TOKEN }}"
          path: "config"

      - name: Clone nixpkgs repository
        uses: actions/checkout@v4
        with:
          repository: "Shawn8901/nixpkgs"
          token: "${{ secrets.GH_TOKEN }}"
          path: "nixpkgs"
          fetch-depth: 0

      - name: Set up git
        shell: bash
        run: |
          git config user.email git@pointjig.de
          git config user.name "Git Bot"
        working-directory: "nixpkgs"

      - name: Sync Unstable
        uses: ./config/.github/actions/update-custom-branch
        with:
          gh_token: "${{ secrets.GH_TOKEN }}"
          release: "unstable"
          working_dir: "nixpkgs"

      - name: Sync 24.11
        uses: ./config/.github/actions/update-custom-branch
        with:
          gh_token: "${{ secrets.GH_TOKEN }}"
          release: "24.11"
          working_dir: "nixpkgs"
